### ISSUE TITLE
Consider using LibFlyable to test for flight access

### ISSUE THREAD

**Issue by pollyzoid** [mbattersby/LiteMount#1]
It's a new library meant to replace IsFlyableArea and fix its bugs. Contributing to it will also benefit other addons looking for a bug-free way to test for flight.

https://wow.curseforge.com/projects/libflyable

**Comment by mbattersby** [comment]
Thanks for the suggestion. I had a look at the library, and I'm already doing a better job, plus Phanx doesn't play WoW any more. I gave them some feedback that they didn't seem to want, so I'll keep an eye on what they're doing but I'm not going to embed their lib.
